version: '3'
volumes:
  pgdata:
  static_files:
services:
  python:
    # image: python:3.4
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=tickets.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 tickets.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: tickets
      POSTGRES_DB: tickets
      POSTGRES_PASS: tickets
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80
